# Site settings
title: eemece2 personal site
email: eemece2 at g
description: > # this means to ignore newlines until "baseurl:"
    eemece2: open source projects, linux, etc.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://eemece2.com" # the base hostname & protocol for your site
twitter_username: eemece2
github_username:  eemece2

# Build settings
markdown: kramdown
